version: "3"

services:
  nuxt-app:
    command: pnpm run dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - nuxt_node_modules:/modules
    ports:
      - 3000:3000

volumes:
  nuxt_node_modules: