import antfu from '@antfu/eslint-config'
import tailwind from 'eslint-plugin-tailwindcss'

export default antfu(
  {
    ignores: [
      // Generated by the shadcn CLI and overwritten on every update; restyling it
      // would only make those updates harder to diff against upstream.
      'app/components/ui/**',
      // Design notes. Their code blocks are illustrative pseudocode, not code that
      // is meant to parse.
      '.docs/**'
    ],
    formatters: {
      prettierOptions: {
        trailingComma: 'none'
      }
    },
    overrides: {
      stylistic: {
        'style/comma-dangle': ['error', 'never']
      }
    },
    rules: {
      'antfu/top-level-function': 'off',
      'ts/consistent-type-definitions': 'off'
    }
  },

  // A flat config since v4, so it plugs in directly; loading it through the legacy
  // FlatCompat bridge fails on its `name` key.
  tailwind.configs.recommended,
  {
    name: 'project/tailwindcss',
    settings: {
      tailwindcss: {
        // Required by v4, which reads the theme from CSS rather than a JS config.
        cssConfigPath: './app/assets/css/tailwind.css'
      }
    },
    rules: {
      'tailwindcss/no-custom-classname': 'off'
    }
  }
)
